language: ruby
bundler_args: --retry=3 --jobs=3
cache: bundler
rvm:
  - 2.2.3
services:
  - mysql
before_script:
  - mysql -e 'create database monitoring_server_test;'
script:
  - export RAILS_ENV=test
  - bundle exec rake db:create db:migrate
  - bundle exec rake db:test:prepare
