default: &default
  adapter: mysql2
  host: localhost
  port: 3306
  encoding: utf8
  pool: 5
  username: <%= ENV['DATABASE_USERNAME'] %>
  password: <%= ENV['DATABASE_PASSWORD'] %>

development:
  <<: *default
  database: monitoring_server_development

test:
  <<: *default
  database: monitoring_server_test

production:
  <<: *default
  database: monitoring_server_production
